name: scaffold_gs
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch=2.1.0
  - torchvision=0.16.0
  - torchaudio=2.1.0
  - pytorch-cuda=12.1
  - plyfile
  - tqdm
  - scipy
  - imageio
  - colorama
  - pip:
    - einops
    - wandb
    - lpips
    - laspy
    - opencv-python
    - torch-scatter
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
